// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4-alpha

package handler

import (
	"net/http"

	test "github.com/shyandsy/shygoctl/demo/internal/handler/test"
	"github.com/shyandsy/shygoctl/demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// get books
				Method:  http.MethodGet,
				Path:    "/book",
				Handler: test.GetBooksHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
