// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4-alpha

package types

import (
	"github.com/shyandsy/goctl/demo/common"
	"time"
)

type Author struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"firstName"`
	BirthYear *int   `json:"birthYear"`
}

type BaseBook struct {
	Name     string     `json:"name"`
	Price    *float32   `json:"name"`
	Authors  []Author   `json:"author"`
	Created  time.Time  `json:"created"`
	Modified *time.Time `json:"modified"`
}

type Book struct {
	Id []int64 `json:"id"`
	BaseBook
	Created  time.Time  `json:"created"`
	Modified *time.Time `json:"modified"`
}

type BasePageResp struct {
	Page  int   `json:"page"`
	Total int64 `json:"total"`
}

type GetBookReq struct {
	common.BasePageReq
}

type GetBookResp struct {
	BasePageResp
	Items []Book `json:"items"`
}
